set_property LOC E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property LOC U9 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property LOC U8 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports en]

set_property LOC P4 [get_ports adjust_hour]
set_property IOSTANDARD LVCMOS33 [get_ports adjust_hour]

set_property LOC P3 [get_ports adjust_minute]
set_property IOSTANDARD LVCMOS33 [get_ports adjust_minute]

set_property LOC N6 [get_ports an[0]]
set_property IOSTANDARD LVCMOS33 [get_ports an[0]]
set_property LOC M6 [get_ports an[1]]
set_property IOSTANDARD LVCMOS33 [get_ports an[1]]
set_property LOC M3 [get_ports an[2]]
set_property IOSTANDARD LVCMOS33 [get_ports an[2]]
set_property LOC N5 [get_ports an[3]]
set_property IOSTANDARD LVCMOS33 [get_ports an[3]]
set_property LOC N2 [get_ports an[4]]
set_property IOSTANDARD LVCMOS33 [get_ports an[4]]
set_property LOC N4 [get_ports an[5]]
set_property IOSTANDARD LVCMOS33 [get_ports an[5]]
set_property LOC L1 [get_ports an[6]]
set_property IOSTANDARD LVCMOS33 [get_ports an[6]]
set_property LOC M1 [get_ports an[7]]
set_property IOSTANDARD LVCMOS33 [get_ports an[7]]

set_property LOC M4 [get_ports sseg[0]]
set_property IOSTANDARD LVCMOS33 [get_ports sseg[0]]
set_property LOC L6 [get_ports sseg[1]]
set_property IOSTANDARD LVCMOS33 [get_ports sseg[1]]
set_property LOC M2 [get_ports sseg[2]]
set_property IOSTANDARD LVCMOS33 [get_ports sseg[2]]
set_property LOC K3 [get_ports sseg[3]]
set_property IOSTANDARD LVCMOS33 [get_ports sseg[3]]
set_property LOC L4 [get_ports sseg[4]]
set_property IOSTANDARD LVCMOS33 [get_ports sseg[4]]
set_property LOC L5 [get_ports sseg[5]]
set_property IOSTANDARD LVCMOS33 [get_ports sseg[5]]
set_property LOC N1 [get_ports sseg[6]]
set_property IOSTANDARD LVCMOS33 [get_ports sseg[6]]
set_property LOC L3 [get_ports sseg[7]]
set_property IOSTANDARD LVCMOS33 [get_ports sseg[7]]

set_property LOC T8 [get_ports tweet]
set_property IOSTANDARD LVCMOS33 [get_ports tweet]
